### ISSUE TITLE
## Linux

### ISSUE THREAD

**Issue by seth4gran** [tech-gamers/backend-rails#25]
## Linux
- [x] 1
- [x] 4.2
- [x] 5
- [x] 6
- [x] 9
- [ ] 10
- [ ] 11.2
- [ ] 12.1
- [ ] 12.2
What's 10 11.2 12.2 and 12.2 and where's 11.6
Also bank account information mid so incorrect 

_Originally posted by @robturtle in https://github.com/tech-gamers/backend-rails/issues/2_

**Comment by robturtle** [comment]
I don't know what r u talking about. This is an organization just created yesterday. If you have any issues related any previous organization under this name, please talk to Github support.
